### ISSUE TITLE
Add Stats Bar Component

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-uikit#76]
A box containing summary statistics for display on entity pages or file browser.

<img width="797" alt="screen shot 2018-12-04 at 11 10 50 am" src="https://user-images.githubusercontent.com/2495894/49455492-498e3d80-f7b5-11e8-8c63-3ed9b8b8f189.png">

Addresses kids-first/kf-ui-release-archives#45

**Comment by bdolly** [comment]
@dankolbman this got released didn't it?
